import type { Listing } from './types'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'listing-001',
    title: 'Bright flat in the Eixample',
    description:
      'A spacious, light-filled flat in the heart of Barcelona\'s Eixample district. High ceilings, original mosaic floors, and a private balcony overlooking a quiet street. Supermarkets, cafés, and the metro are all within a 5-minute walk.',
    propertyType: 'flat',
    location: {
      city: 'Barcelona',
      country: 'Spain',
      coordinates: { lat: 41.3918, lng: 2.1649 },
    },
    host: {
      id: 'host-001',
      name: 'Marta Puig',
      avatarUrl: 'https://picsum.photos/seed/host001/100/100',
      memberSince: '2021-03-15',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing001a/800/600', alt: 'Bright living room with large windows and mosaic floor tiles' },
      { url: 'https://picsum.photos/seed/listing001b/800/600', alt: 'Modern kitchen with white cabinets and marble countertop' },
    ],
    amenities: ['Wi-Fi', 'Air conditioning', 'Washing machine', 'Elevator', 'Balcony'],
    nightlyRate: 95,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: 'listing-002',
    title: 'Cosy studio near Prenzlauer Berg',
    description:
      'A well-designed studio apartment in a quiet side street off Prenzlauer Berg. Features a fully equipped kitchen, a comfortable sofa bed, and fast Wi-Fi. Close to tram lines, independent coffee shops, and weekend markets.',
    propertyType: 'studio',
    location: {
      city: 'Berlin',
      country: 'Germany',
      coordinates: { lat: 52.5396, lng: 13.4151 },
    },
    host: {
      id: 'host-002',
      name: 'Jonas Weber',
      avatarUrl: null,
      memberSince: '2022-07-01',
      verifiedHost: false,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing002a/800/600', alt: 'Open-plan studio with sofa bed and kitchen area' },
      { url: 'https://picsum.photos/seed/listing002b/800/600', alt: 'Compact desk workspace by a large window' },
    ],
    amenities: ['Wi-Fi', 'Heating', 'Fully equipped kitchen', 'Bicycle storage'],
    nightlyRate: 65,
    maxGuests: 2,
    bedrooms: 0,
    bathrooms: 1,
    rating: 4.5,
    reviewCount: 18,
  },
  {
    id: 'listing-003',
    title: 'Traditional house in Alfama',
    description:
      'An authentic Alfama townhouse spread over three floors, with a rooftop terrace offering panoramic views of the Tagus river. Original azulejo tiles throughout. Close to the castle, fado venues, and the tram 28 route.',
    propertyType: 'house',
    location: {
      city: 'Lisbon',
      country: 'Portugal',
      coordinates: { lat: 38.7139, lng: -9.1334 },
    },
    host: {
      id: 'host-003',
      name: 'Inês Ferreira',
      avatarUrl: 'https://picsum.photos/seed/host003/100/100',
      memberSince: '2020-11-20',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing003a/800/600', alt: 'Rooftop terrace with river view and terracotta pots' },
      { url: 'https://picsum.photos/seed/listing003b/800/600', alt: 'Traditional living room with azulejo-tiled walls' },
    ],
    amenities: ['Wi-Fi', 'Rooftop terrace', 'Washing machine', 'Air conditioning', 'Towels & linen'],
    nightlyRate: 145,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    rating: null,
    reviewCount: 0,
  },
  {
    id: 'listing-004',
    title: 'Canal-view flat in Jordaan',
    description:
      'A charming flat on the second floor of a classic Dutch canal house in the Jordaan neighbourhood. Original wooden beams, large sash windows overlooking the canal, and a fully equipped kitchen. Perfect for exploring Amsterdam on foot or by bike.',
    propertyType: 'flat',
    location: {
      city: 'Amsterdam',
      country: 'Netherlands',
      coordinates: { lat: 52.3750, lng: 4.8840 },
    },
    host: {
      id: 'host-004',
      name: 'Lotte de Vries',
      avatarUrl: 'https://picsum.photos/seed/host004/100/100',
      memberSince: '2019-06-10',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing004a/800/600', alt: 'Living room with canal view and original wooden beams' },
      { url: 'https://picsum.photos/seed/listing004b/800/600', alt: 'Cosy bedroom with white linen and exposed brickwork' },
    ],
    amenities: ['Wi-Fi', 'Bicycle hire available', 'Canal view', 'Dishwasher', 'Heating'],
    nightlyRate: 130,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    rating: 4.9,
    reviewCount: 61,
  },
  {
    id: 'listing-005',
    title: 'Sunny room in Ruzafa',
    description:
      'A private en-suite room in a shared flat in Valencia\'s trendiest neighbourhood, Ruzafa. Shared common areas are clean and well-maintained. Great natural light, close to independent restaurants and the weekly vintage market.',
    propertyType: 'room',
    location: {
      city: 'Valencia',
      country: 'Spain',
      coordinates: { lat: 39.4561, lng: -0.3772 },
    },
    host: {
      id: 'host-005',
      name: 'Pablo Navarro',
      avatarUrl: null,
      memberSince: '2023-01-05',
      verifiedHost: false,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing005a/800/600', alt: 'Bright en-suite room with double bed and tiled floor' },
      { url: 'https://picsum.photos/seed/listing005b/800/600', alt: 'Shared kitchen with large table and colourful tiles' },
    ],
    amenities: ['Wi-Fi', 'En-suite bathroom', 'Air conditioning', 'Shared kitchen'],
    nightlyRate: 45,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    rating: 4.2,
    reviewCount: 9,
  },
  {
    id: 'listing-006',
    title: 'Historic flat in Ribeira',
    description:
      'A beautifully restored flat in Porto\'s historic Ribeira quarter, a UNESCO World Heritage site. Stone walls, wooden floors, and a small balcony. Walking distance from the Dom Luís I Bridge, wine cellars, and the riverfront.',
    propertyType: 'flat',
    location: {
      city: 'Porto',
      country: 'Portugal',
      coordinates: { lat: 41.1407, lng: -8.6145 },
    },
    host: {
      id: 'host-006',
      name: 'Carlos Mendes',
      avatarUrl: 'https://picsum.photos/seed/host006/100/100',
      memberSince: '2021-09-18',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing006a/800/600', alt: 'Living room with stone walls and wooden flooring' },
      { url: 'https://picsum.photos/seed/listing006b/800/600', alt: 'Small balcony overlooking the Douro riverfront' },
    ],
    amenities: ['Wi-Fi', 'Washing machine', 'Balcony', 'Heating', 'Towels & linen'],
    nightlyRate: 110,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    rating: null,
    reviewCount: 0,
  },
  {
    id: 'listing-007',
    title: 'Cosy Trastevere studio',
    description:
      'A quiet, romantic studio in Rome\'s Trastevere neighbourhood. Terracotta floors, exposed brick, and a small courtyard entrance. Steps from traditional trattorias, artisan workshops, and the Tiber river. Public transport links to the main sights.',
    propertyType: 'studio',
    location: {
      city: 'Rome',
      country: 'Italy',
      coordinates: { lat: 41.8890, lng: 12.4698 },
    },
    host: {
      id: 'host-007',
      name: 'Giulia Romani',
      avatarUrl: 'https://picsum.photos/seed/host007/100/100',
      memberSince: '2020-04-22',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing007a/800/600', alt: 'Studio with terracotta floors and exposed brick wall' },
      { url: 'https://picsum.photos/seed/listing007b/800/600', alt: 'Compact but well-equipped kitchen with courtyard view' },
    ],
    amenities: ['Wi-Fi', 'Air conditioning', 'Espresso machine', 'Towels & linen'],
    nightlyRate: 85,
    maxGuests: 2,
    bedrooms: 0,
    bathrooms: 1,
    rating: 4.7,
    reviewCount: 27,
  },
  {
    id: 'listing-008',
    title: 'Family house in Croix-Rousse',
    description:
      'A spacious family house on Lyon\'s historic Croix-Rousse hillside, known for its silk-weaving heritage and lively morning market. Private garden, three bedrooms, and a large kitchen perfect for self-catering. Funicular to city centre runs nearby.',
    propertyType: 'house',
    location: {
      city: 'Lyon',
      country: 'France',
      coordinates: { lat: 45.7745, lng: 4.8302 },
    },
    host: {
      id: 'host-008',
      name: 'Sophie Marchand',
      avatarUrl: 'https://picsum.photos/seed/host008/100/100',
      memberSince: '2018-12-03',
      verifiedHost: true,
    },
    photos: [
      { url: 'https://picsum.photos/seed/listing008a/800/600', alt: 'Garden with wooden table and chairs surrounded by greenery' },
      { url: 'https://picsum.photos/seed/listing008b/800/600', alt: 'Large open-plan kitchen and dining area with natural light' },
    ],
    amenities: ['Wi-Fi', 'Private garden', 'Washing machine', 'Dishwasher', 'Parking', 'Heating'],
    nightlyRate: 185,
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4.6,
    reviewCount: 43,
  },
]
